# ---------- ETAPA 1: Build ----------
FROM node:22-alpine as build

WORKDIR /app

# Argumento para la URL de la API
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build-only

# ---------- ETAPA 2: Servir ----------
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

# Copiar configuración de nginx para manejar SPA
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
