# Imagen base ligera
FROM node:22-alpine

# Carpeta dentro del contenedor
WORKDIR /app

# Copiar dependencias primero (mejora caché)
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Construir proyecto
RUN npm run build

# Exponer puerto
EXPOSE 3000

# Comando para arrancar
CMD ["node", "dist/main.js"]